version: '3.8'

services:
  app:
    build: .
    container_name: spring-app
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: